### ISSUE TITLE
Subset of 444 samples

### ISSUE THREAD

**Issue by Chao0511** [SPRIGHT-T2I/SPRIGHT#6]
Hello,

Thanks for the code!

Just a small question: where may I find the subset of 444 samples, where each image has >18 objects?
i.e. the subset that you finetuned SD2.1 on it and got 0.2133 T2I-CompBench Spatial score.

Many thanks!

**Comment by agneet42** [comment]
Hi,

Thanks for your interest in our work. Out of the 444 images, 200 are from Segment Anything and the rest are from LAION. We are not able to share the LAION images at this time, because the parent images are not public. However, we are happy to share the 200 from SA. Let us know if that suffices for you.

Thanks.

**Comment by Chao0511** [comment]
Hello,

Yes that would also be great. Where may I find the 200 (img, recaptioned prompt) samples from SA? Many thanks. :)

Best regards,

**Comment by agneet42** [comment]
Will share that shortly. Stay tuned!

**Comment by agneet42** [comment]
@Chao0511 here you go - https://huggingface.co/datasets/SPRIGHT-T2I/18_obj_444

We will update the LAION images in due course. 
If this resolves your issue, please feel free to close it, thanks!

**Comment by Chao0511** [comment]
Yes, many thanks!
